name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Install ko
      uses: ko-build/setup-ko@v0.7
      env:
        KO_DOCKER_REPO: us-east4-docker.pkg.dev/minder-zoo/banditize

    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/2476835098/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions
        project_id: minder-zoo

    - name: Build and push to container registry
      id: build
      run: echo "image=$(ko build)" >> $GITHUB_OUTPUT
      env:
        # Build on the bandit base image, adding our container and overwriting the entrypoint
        KO_DEFAULTBASEIMAGE: ghcr.io/pycqa/bandit/bandit@sha256:82b81adc7ac8394e35da72fd34eb56a5d56f8a32bfec7bf1b8ad9188a840ac89

    - name: Push to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        image: "${{ steps.build.outputs.image}}"
        service: banditize
        region: us-central1